### ISSUE TITLE
please add transferable support feature

### ISSUE THREAD

**Issue by yokewang** [AndersCan/typed-web-workers#2]
I have make a tiny change to your code. Although it runs well but I am not sure it's correct for every case.
```
 TypedWorker.prototype.postMessage = function (workerMessage) {
        if (workerMessage.transferList)
          this._nativeWorker.postMessage(workerMessage, workerMessage.transferList);
        else
          this._nativeWorker.postMessage(workerMessage);
    };
```

**Comment by AndersCan** [comment]
Hey @yokewang 

`transferList` is not something that I have used before so I am unfamiliar with its use cases. I will take a look later this week and see how I can implement it.

**Comment by AndersCan** [comment]
Progress started at [feature/ISU-2](https://github.com/AndersCan/typed-web-workers/tree/feature/ISU-2)

**Comment by AndersCan** [comment]
Sorry it took so long, I ended up doing a larger refactor. Please take a look at [the transfer spec](https://github.com/AndersCan/typed-web-workers/blob/v2.1.1/test/Transfer.spec.ts) to see how you can transfer ownership.

Let me know if anything is unclear.
