### ISSUE TITLE
Example doesn't work. No import statement.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [AndersCan/typed-web-workers#3]
The example code on your github page doesn't work. There is no import statement. After running the npm i -S typed-web-workers I look through my node_modules directory and see nothing that seems to relate to this module.

Please post a complete working example.

**Comment by AndersCan** [comment]
Thanks for pointing this out. I'll update the readme and create an example file later today.

**Comment by AndersCan** [comment]
Added a import line to the readme. Should be faily clear now how to use this. If anyone needs a full example file, they can look in the `test` folder.

After running `npm install typed-web-workers` in a new project, I can see the corresponding folder `node_modules/typed-web-workers`. Not sure why you are unable to find it.
