### ISSUE TITLE
Async task in worker function

### ISSUE THREAD

**Issue by Anil8753** [AndersCan/typed-web-workers#5]
typed worker doing its job nicely, but I have a case. I need to do an async operation in worker function.

```
function workFn(input: Values): number {
 return input.x + input.y
}

```

In the above function, simply returning **return input.x + input.y** I need to do some async operation.
We can simulate it via 

```
  setTimeout(()=>{
      // Some task
      return input.x + input.y
  }, 10);
```

How can I achieve it.

```
interface Values {
  x: number
  y: number
}

function workFn(input: Values): number {
 // return input.x + input.y

  setTimeout(()=>{
      return input.x + input.y
  }, 10);
}

function logFn(result: number) {
  console.log(`We received this response from the worker: ${result}`)
}
 
const typedWorker = new TypedWorker(workFn, logFn)
typedWorker.postMessage({ x: 5, y: 5 }) // logs: "10"
```

**Comment by AndersCan** [comment]
I've thought about this before, but I have not decided on what the best course of action is. 

Simplest solution would be to pass an extra parameter that is the `postMessage` function  to the `workFn`. That would allow multiple returns.

I'll investigate and get back to you.

**Comment by AndersCan** [comment]
I ended up rewriting a bit to allow for async tasks in the worker function. Please check the updated readme, migration guide and download v2 from npm.

Please let me know if you have any questions.
