### ISSUE TITLE
Wrong type in example?

### ISSUE THREAD

**Issue by ottosson** [AndersCan/typed-web-workers#8]
I tried to copy one of the examples to a small test project, but I get a type error:

```
class myClass {

  constructor() {
    const typedWorker: ITypedWorker<number, number> = createWorker(this.workFn, this.logFn);
  }

  private workFn(input: Values, callback: (_: number) => void): void {
    callback(input.x + input.y);
  }

  private logFn(result: number) {
    console.log(`We received this response from the worker: ${result}`);
  }
}
```
> Type 'ITypedWorker<Values, number>' is not assignable to type 'ITypedWorker<number, number>'.
>   Type 'Values' is not assignable to type 'number'.

Is the example wrong or have I missed something? I can't really figure it out =/

**Comment by AndersCan** [comment]
Hey @ottosson,
You are absolutely correct, there is a mistake in the readme file.
It should be:
`const typedWorker: ITypedWorker<Values, number> = createWorker(this.workFn, this.logFn);`

Sorry about that, I'll fix it asap.

**Comment by ottosson** [comment]
Excellent, thanks!

There's also a typo in the second workFn example where there are one ")" too many:
```
// --------------------------------------------------------- V here.
function workFn(input: Values, callback: (_: number) => void)): void {
  callback(input.x + input.y)
}
```

**Comment by AndersCan** [comment]
Writing the readme has been the most challenging part of this library.

Thanks for pointing out the mistake.

**Comment by ottosson** [comment]
Hehe, I can only imagine ;)

Now it looks good. Thanks!
