### ISSUE TITLE
No error handling?

### ISSUE THREAD

**Issue by burtonator** [AndersCan/typed-web-workers#9]
Is it just me do you assume that everything executes successfully. I think you need to throw in a try/catch so that you can have an Error on the callback ...

**Comment by AndersCan** [comment]
I think it is better to just have a try/catch in the workerFunction that you pass in. Have not tested this thoroughly, but it should work:
```javascript
const tryWorker: ITypedWorker<number, string> = createWorker(
  (input, cb) => {
    try {
      if (Math.random() > 0.5) {
        cb('ok')
      } else {
        throw 'not ok'
      }
    } catch (e) {
      cb(e)
    }
  },
  output => {
    // test if output is ok or not ok
  }
)
```
